version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: keycloak_demo
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    ports:
      - "8080:8080"  # Keycloak default port
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/my_database
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=password
    volumes:
      - "${HOME}/docker_volumes/keycloak:/opt/keycloak/data"
    depends_on:
      - postgres
    command: start-dev

volumes:
  postgres_data:
